FROM rocker/rstudio:4.1.1

RUN git clone https://github.com/schalkdaniel/simulations-distr-auc /home/rstudio/simulations-distr-auc
RUN Rscript R/install-pkgs-versions.R
RUN echo "setwd('/home/rstudio/simulations-distr-auc')" >> /home/rstudio/.Rprofile
