---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment  = "#>",
  fig.path = "figures/",
  warning  = FALSE,
  message  = FALSE
)

use_font = TRUE

## ============================================================== ##
##
##                              SETUP
##
## ============================================================== ##

# source(here::here("R/install-pkgs-versions.R"))

library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(ggsci)
library(ggridges)
library(knitr)

### Figure setup:
if (use_font) {
  font = "TeX Gyre Bonum"

  sysfonts::font_add(font,
      regular = "/usr/share/texmf-dist/fonts/opentype/public/tex-gyre/texgyrebonum-regular.otf",
      bold = "/usr/share/texmf-dist/fonts/opentype/public/tex-gyre/texgyrebonum-bold.otf")
  extrafont::font_import(paths = "~/repos/bm-CompAspCboost/paper-figures/gyre-bonum", prompt = FALSE)
  extrafont::loadfonts()

  theme = theme_minimal(base_family = font)
} else {
  theme = theme_minimal()
}

theme_set(
  theme +
  ggplot2::theme(
    strip.background = element_rect(fill = "white", color = "black"),
    strip.text = element_text(color = "black", face = "bold", size = 7),
    axis.text = element_text(size = 7),
    axis.title = element_text(size = 9),
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 6),
    panel.border = element_rect(colour = "black", fill = NA, size = 0.5)
  )
)

my_color = scale_color_uchicago()
my_fill = scale_fill_uchicago()

g_legend = function(a_gplot) {
  tmp = ggplot_gtable(ggplot_build(a_gplot))
  leg = which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend = tmp$grobs[[leg]]
  return(legend)
}

# to determine width, use the latex package `layouts` and put
# `\printinunitsof{mm}\prntlen{\textwidth}` into the tex file.
textwidth = 148.92

## Helper functions:
logitToAUC = function(x) 1 / (1 + exp(-x))
```

## Simulation Results

```{r}
## Load data

### Load ROC-GLM approximation::
load(here::here("data/ll_aucs_range.Rda"))
aucs_emp = do.call(rbind, lapply(ll_aucs, function(ll) ll$aucs))


### Load Distributed ROC-GLM approximations:
app_acc = rbind(
  data.frame(lower = 0, upper = (0.8 - 0.6) * 1 / 100, qual = "use-case"),
  data.frame(lower = (0.8 - 0.6) * 1 / 100, upper = (1 - 0.5) * 1 / 100, qual = "general"),
  data.frame(lower = (1 - 0.5) * 1 / 100, upper = Inf, qual = "unacceptable")
)

if (file.exists(here::here("data/aucs_distr_noise.Rda"))) {
  load(here::here("data/aucs-distr-noise.Rda"))
} else{
  load(here::here("data/ll_aucs_nfacs.Rda"))
  aucs_distr = do.call(rbind, lapply(ll_aucs_nfacs, function(lla) {
    do.call(rbind, apply(lla, 1, function(ll) {
      cbind(ll[[1]]$aucs, noisef = ll$nfac, margin = ll$margin)
    }))
  }))
  aucs_distr = aucs_distr %>%
    mutate(
      auc_diff = abs(auc_emp - auc_roc),
      qual = cut(auc_diff, breaks = c(app_acc$lower, Inf), labels = app_acc$qual),
      margin_rel = margin / n)

  save(aucs_distr, file = here::here("data/aucs-distr-noise.Rda"))
}


### Load confidence Intervals (CIs):
cis = do.call(rbind, lapply(ll_aucs, function(ll) {
  cbind(ll$cis, ll$aucs[rep(1, 4), ])
}))

cis = cis %>%
  group_by(n, npos, threshold) %>%
  mutate(
    auc_lower_diff = logitToAUC(lower) - logitToAUC(lower[method == "DeLong Empirical"]),
    auc_upper_diff = logitToAUC(upper) - logitToAUC(upper[method == "DeLong Empirical"])
  )
```

## Figures

### AUC density

```{r}
gg_den_both = ggplot(data = aucs_emp) +
  geom_histogram(aes(x = auc_emp, color = "Empirical AUC", fill = "Empirical AUC", y = ..density..),
     color = "white", size = 0.2, alpha = 0.4) +
  geom_histogram(aes(x = auc_roc, color = "AUC (ROC-GLM)", fill = "AUC (ROC-GLM)", y = ..density..),
     color = "white", size = 0.2, alpha = 0.2) +
  geom_histogram(aes(x = auc_emp, color = "Empirical AUC", fill = "Empirical AUC", y = ..density..),
     color = "white", size = 0.2, alpha = 0) +
  geom_density(aes(x = auc_emp, color = "Empirical AUC", fill = "Empirical AUC"),
     fill = "transparent", size = 0.6, alpha = 0.4) +
  geom_density(aes(x = auc_roc, color = "AUC (ROC-GLM)", fill = "AUC (ROC-GLM)"),
     fill = "transparent", size = 0.6, alpha = 0.2) +
  theme(legend.position = "bottom", legend.key.size = unit(0.2, 'cm')) +
  xlab("AUC") +
  ylab("Density") +
  labs(fill = "", color = "") +
  my_fill + my_color

gg_den_both

ggsave(plot = gg_den_both,
  filename = here::here("figures/auc-emp-density.pdf"),
  width = textwidth * 0.4,
  height = textwidth * 1/4,
  units = "mm")
```

### Compare CIs

```{r}
cis$ci_range = cis$upper - cis$lower
nb = c(0, 200, 400, 800, 1600, 3200)

cis_plt = cis %>%
  pivot_longer(cols = c("lower", "upper"), names_to = "ci") %>%
  mutate(
    auc_cat = cut(auc_emp, breaks = seq(0.5, 1, length.out = 11L)),
    n_cat = cut(n, breaks = nb, labels = paste0("n in (", nb[-length(nb)], ", ", nb[-1], "]")),
    value = logitToAUC(value)) %>%
  select(-noise) %>%
  na.omit()

#gg_short = cis_plt %>% filter(((n > 200) & (n < 400)) | ((n > 1600 & n < 3200))) %>% filter(auc_cat %in% c("(0.5,0.55]", "(0.7,0.75]")) %>%
gg_cis = cis_plt %>%
  ggplot(aes(x = value, fill = ci, y = method, color = ci)) +
  geom_density_ridges(alpha = 0.5, rel_min_height = 0.01, show.legend = FALSE) + #, color = "transparent") +
  #theme_ridges(grid = TRUE, center_axis_labels = TRUE) +
  scale_x_continuous(breaks = seq(0.5, 1, 0.1)) +
  xlab("AUC") +
  ylab("") +
  labs(fill = "CI Boundary") +
  facet_grid(paste0("AUC in\n", auc_cat) ~ n_cat) +
  ggtitle("Comparison of 95 % AUC CIs", subtitle = paste0("Lower CI (red) and upper CI (gray) of ", nrow(aucs_emp), " repetitions")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  my_color + my_fill

gg_cis

ggsave(plot = gg_cis,
  filename = here::here("figures/auc-cis.pdf"),
  width    = textwidth * 1.2,
  height   = textwidth * 1.3,
  units    = "mm")
```

### Approximation errors

```{r}
tab = aucs_distr %>% mutate(
    auc_diff    = auc_emp - auc_roc,
    auc_app_cut = cut(x = auc_roc, breaks = seq(0.5, 1, length.out = 21L)),
    auc_emp_cut = cut(x = auc_emp, breaks = seq(0.5, 1, length.out = 21L))
  ) %>%
  group_by(auc_emp_cut, noisef, margin) %>%
  summarize(
    Min.      = min(auc_diff, na.rm = TRUE),
    "1st Qu." = quantile(auc_diff, 0.25, na.rm = TRUE),
    Median    = median(auc_diff, na.rm = TRUE),
    Mean      = mean(auc_diff, na.rm = TRUE),
    "3rd Qu." = quantile(auc_diff, 0.75, na.rm = TRUE),
    Max.      = max(auc_diff, na.rm = TRUE),
    Sd.       = sd(auc_diff, na.rm = TRUE),
    Count     = n()) %>%
  mutate(qual = cut(abs(Mean), breaks = c(app_acc$lower, Inf), labels = app_acc$qual))

tab$qual = factor(tab$qual, levels = c("unacceptable", "general", "use-case"))

gg_dist = ggplot(na.omit(tab), aes(x = "1", y = auc_emp_cut, color = qual, fill = qual)) +
  geom_tile() +
  scale_y_discrete(limits = rev, breaks = levels(tab$auc_emp_cut)[c(5, 16)]) +
  xlab("") +
  theme(axis.text.x = element_blank()) +
  ylab("AUC bin") +
  scale_color_npg() + scale_fill_npg() + # Looks nicer than uchicago
  #my_color + my_fill +
  labs(color = "Accuracy", fill = "Accuracy") +
  facet_grid(noisef ~ margin)

gg_dist

ggsave(plot = gg_dist,
  filename = here::here("figures/auc-distr.pdf"),
  width = textwidth * 0.8,
  height = textwidth * 0.8,
  units = "mm")
```

## Tables

```{r}
tab = aucs_emp %>% mutate(
    auc_diff = auc_emp - auc_roc,
    auc_app_cut = cut(x = auc_roc, breaks = seq(0.5, 1, length.out = 21L)),
    auc_emp_cut = cut(x = auc_emp, breaks = seq(0.5, 1, length.out = 21L))
  ) %>%
  group_by(auc_emp_cut) %>%
  summarize(Min. = min(auc_diff, na.rm = TRUE), "1st Qu." = quantile(auc_diff, 0.25, na.rm = TRUE),
    Median = median(auc_diff, na.rm = TRUE), Mean = mean(auc_diff, na.rm = TRUE), "3rd Qu." = quantile(auc_diff, 0.75, na.rm = TRUE),
    Max. = max(auc_diff, na.rm = TRUE), Sd. = sd(auc_diff, na.rm = TRUE), Count = n())

tab_latex = tab %>% kable(format = "latex")
writeLines(tab_latex, here::here("tables/auc-approximations.tex"))

tab %>% kable()
```
