install.packages('remotes')
remotes::install_version("here", version = "0.1", upgrade = FALSE)
remotes::install_version("dplyr", version = "1.0.8", upgrade = FALSE)
remotes::install_version("tidyr", version = "1.2.0", upgrade = FALSE)
remotes::install_version("ggplot2", version = "3.3.5", upgrade = FALSE)
remotes::install_version("gridExtra", version = "2.3", upgrade = FALSE)
remotes::install_version("ggsci", version = "2.9", upgrade = FALSE)
remotes::install_version("ggridges", version = "0.5.3", upgrade = FALSE)
remotes::install_version("knitr", version = "1.36", upgrade = FALSE)
remotes::install_version("pROC", version = "1.18.0", upgrade = FALSE)
remotes::install_version("batchtools", version = "0.9.15", upgrade = FALSE)
remotes::install_version("sysfonts", version = "0.8.1", upgrade = FALSE)
remotes::install_version("extrafont", version = "0.17", upgrade = FALSE)
remotes::install_version("ggridges", version = "0.5.3", upgrade = FALSE)
remotes::install_version("ggsci", version = "2.9", upgrade = FALSE)
remotes::install_version("latex2exp", version = "0.5.0", upgrade = FALSE)
remotes::install_version("jsonlite", version = "1.7.3", upgrade = FALSE)
